spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    h2:
      console:
        enabled: true
  datasource:
    data: classpath:db/migration/V3__Insert_default_data.sql

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
