SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE orders RESTART IDENTITY;
TRUNCATE TABLE order_line_item RESTART IDENTITY;
TRUNCATE TABLE order_table RESTART IDENTITY;
TRUNCATE TABLE table_group RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE
