SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE ORDERS;
ALTER TABLE ORDERS ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE ORDER_LINE_ITEM;
ALTER TABLE ORDER_LINE_ITEM ALTER COLUMN SEQ RESTART WITH 1;

TRUNCATE TABLE MENU;
ALTER TABLE MENU ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE MENU_GROUP;
ALTER TABLE MENU_GROUP ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE MENU_PRODUCT;
ALTER TABLE MENU_PRODUCT ALTER COLUMN SEQ RESTART WITH 1;

TRUNCATE TABLE ORDER_TABLE;
ALTER TABLE ORDER_TABLE ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE TABLE_GROUP;
ALTER TABLE TABLE_GROUP ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE PRODUCT;
ALTER TABLE PRODUCT ALTER COLUMN ID RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;
