SET REFERENTIAL_INTEGRITY FALSE

TRUNCATE TABLE PRODUCT
TRUNCATE TABLE MENU_GROUP
TRUNCATE TABLE MENU_PRODUCT
TRUNCATE TABLE MENU
TRUNCATE TABLE ORDERS
TRUNCATE TABLE ORDER_LINE_ITEM
TRUNCATE TABLE ORDER_TABLE
TRUNCATE TABLE TABLE_GROUP

SET REFERENTIAL_INTEGRITY TRUE
