SET FOREIGN_KEY_CHECKS = false;

TRUNCATE TABLE order_line_item RESTART IDENTITY;
TRUNCATE TABLE orders RESTART IDENTITY;
TRUNCATE TABLE menu_product RESTART IDENTITY;
TRUNCATE TABLE kitchenpos.product.product RESTART IDENTITY;
TRUNCATE TABLE kitchenpos.product.menu RESTART IDENTITY;
TRUNCATE TABLE order_table RESTART IDENTITY;
TRUNCATE TABLE menu_group RESTART IDENTITY;
TRUNCATE TABLE table_group RESTART IDENTITY;

SET FOREIGN_KEY_CHECKS = true;
