###
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "후라이드 * 2",
  "price": 19000,
  "menuGroupId": 5,
  "menuProducts": [
    {
      "productId": 6,
      "quantity": 3
    }
  ]
}

###
GET {{host}}/api/menus

###
