###
POST {{host}}/api/orders
Content-Type: kitchenpos.menu/json

{
  "orderTableId": 1,
  "orderLineItems": [
    {
      "menuId": 1,
      "quantity": 1
    }
  ]
}

###
GET {{host}}/api/orders

###
PUT {{host}}/api/orders/1/kitchenpos.order-status
Content-Type: kitchenpos.menu/json

{
  "orderStatus": "MEAL"
}

###
PUT {{host}}/api/orders/1/kitchenpos.order-status
Content-Type: kitchenpos.menu/json

{
  "orderStatus": "COMPLETION"
}

###
