###
POST {{host}}/api/kitchenpos.application.table-groups
Content-Type: application/json

{
  "orderTables": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

###
DELETE {{host}}/api/kitchenpos.application.table-groups/1

###
