###
POST {{host}}/api/tables
Content-Type: application/json

{
  "numberOfGuests": 0,
  "empty": true
}

###
GET {{host}}/api/tables

###
PUT {{host}}/api/tables/1/empty?empty=false
Content-Type: application/json


###
PUT {{host}}/api/tables/1/number-of-guests?numberOfGuests=4
Content-Type: application/json


###
PUT {{host}}/api/tables/1/empty?empty=true
Content-Type: application/json


###
PUT {{host}}/api/tables/2/empty?empty=true
Content-Type: application/json


###
