###
POST {{host}}/api/tables
Content-Type: application/json

{
  "numberOfGuests": 0,
  "orderAvailable": true
}

###
GET {{host}}/api/tables

###
PUT {{host}}/api/tables/1/orderAvailable
Content-Type: application/json

{
  "orderAvailable": false
}

###
PUT {{host}}/api/tables/1/number-of-guests
Content-Type: application/json

{
  "numberOfGuests": 4
}

###
PUT {{host}}/api/tables/1/orderAvailable
Content-Type: application/json

{
  "orderAvailable": true
}

###
PUT {{host}}/api/tables/2/orderAvailable
Content-Type: application/json

{
  "orderAvailable": true
}

###
