@startuml
package MenuPackage #DDDDDD {
  class MenuService
  class Menu
  class MenuProduct
  interface MenuRepository
}
package MenuGroupPackage #DDDDDD {
  class MenuGroupService
  class MenuGroup
  interface MenuGroupRepository
}
package OrderPackage #DDDDDD {
  class OrderService
  class Order
  class OrderLineItem
  interface OrderRepository
}
package ProductPackage #DDDDDD {
  class ProductService
  class Product
  interface ProductRepository
}
package TablePackage #DDDDDD {
  class TableService
  class TableGroupService
  class OrderTable
  class TableGroup
  interface OrderTableRepository
  interface TableGroupRepository
}

  ProductPackage <-[thickness=8]- MenuPackage
  MenuGroupPackage <-[thickness=8]- MenuPackage
  MenuPackage <-[thickness=8]- OrderPackage
  TablePackage <-[thickness=8]- OrderPackage
  OrderPackage <-[thickness=8]- TablePackage


  Menu <-- MenuService
  'MenuGroup <-- MenuService
  MenuGroupRepository <-- MenuService
  MenuProduct <-- MenuService
  MenuRepository <-- MenuService
  Product <-- MenuService
  ProductRepository <-- MenuService

  'MenuGroup <-- Menu

  'Product <-- MenuProduct

  MenuGroup <-- MenuGroupService
  MenuGroupRepository <-- MenuGroupService
'------------------------------------------------------
  'OrderTable <-- Order

  'Menu <-- OrderLineItem

  'Menu <-- OrderService
  MenuRepository <-- OrderService
  Order <-- OrderService
  OrderLineItem <-- OrderService
  OrderRepository <-- OrderService
  OrderTable <-- OrderService
  OrderTableRepository <-- OrderService

  Product <-- ProductService
  ProductRepository <-- ProductService

  OrderTable <-- TableGroup

  OrderRepository <-- TableGroupService
  'OrderTable <-- TableGroupService
  'OrderTableRepository <-- TableGroupService
  TableGroup <-- TableGroupService
  TableGroupRepository <-- TableGroupService

  'OrderRepository <-- TableService
  'OrderTable <-- TableService
  OrderTableRepository <-- TableService

  TableGroup <-- TableGroupRepository
  Order <-- OrderRepository
  Menu <-- MenuRepository
  OrderTableRepository <-- TableService
  OrderTable <-- OrderTableRepository
@enduml