SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE MENU;
ALTER TABLE MENU ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE MENU_GROUP;
ALTER TABLE MENU_GROUP ALTER COLUMN ID RESTART WITH 1;

TRUNCATE TABLE MENU_PRODUCT;
ALTER TABLE MENU_PRODUCT ALTER COLUMN SEQ RESTART WITH 1;

TRUNCATE TABLE PRODUCT;
ALTER TABLE PRODUCT ALTER COLUMN ID RESTART WITH 1;

SET FOREIGN_KEY_CHECKS = 1;
