SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE MENU RESTART IDENTITY;
TRUNCATE TABLE MENU_GROUP RESTART IDENTITY;
TRUNCATE TABLE MENU_PRODUCT RESTART IDENTITY;
TRUNCATE TABLE ORDER_LINE_ITEM RESTART IDENTITY;
TRUNCATE TABLE ORDER_TABLE RESTART IDENTITY;
TRUNCATE TABLE PRODUCT RESTART IDENTITY;
TRUNCATE TABLE ORDERS RESTART IDENTITY;
TRUNCATE TABLE TABLE_GROUP RESTART IDENTITY;

SET FOREIGN_KEY_CHECKS = 1;
